---
- name: setup config ip for interface + Save backup
  hosts: routers
  connection: network_cli
  gather_facts: no 
  tasks:
    - name: configure provider
      set_fact:
        provider:
          username: jalen
          password: password
          auth_pass: cisco

    - name: interface IP address
      ios_config:
        provider: "{{ provider }}"
        authorize: yes
        lines:
        - description Testing for Ansible and IP Assignment
        - ip address 192.168.2.10 255.255.255.0
        - no shutdown
        parents: interface gigabitEthernet 0/1

    - name: run show ip interface brief + ip route
      ios_command:
        commands:
          - show run
      register: output

    - name: print output
      debug:
        var: output.stdout_lines

    - name: backup to tftp server
      copy:
        content: "{{ output.stdout[0] }}"
        dest: "/srv/tftp/ansible-confg"
