---
   - name: capture show output
     hosts: routers
     gather_facts: no
     connection: network_cli

     tasks:
        - name: show run
          ios_command:
            commands:
            - show running-config
            - show ip route
            - show ip eigrp neighbors
            - show version
          register: config

        - name: output message
          debug:
            var: config
